#!/usr/bin/env python3
"""Generate the Lean Blueprint from the manuscript correspondence ledger."""

from __future__ import annotations

import argparse
from collections import Counter
import json
import re
from pathlib import Path

from dump_theorems_with_lean import BEGIN_RE, extract_manuscript


REF_RE = re.compile(r"\\(?:Cref|cref|ref)\{([^}]*)\}")
PROOF_RE = re.compile(r"\\begin\{proof\}.*?\\end\{proof\}", re.S)

# The Lean library namespace used to qualify unqualified declaration names in
# the correspondence ledger. Keep in sync with the lean_lib name in lakefile.toml.
LEAN_LIB = "Conjecture"


def tex_text(value: str) -> str:
    """Escape plain ledger prose for inclusion in LaTeX."""
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        # Ledger prose frequently names long Lean declarations.  Give TeX a
        # legal break point after every underscore so those names cannot run
        # through the print margin.
        "_": r"\_\allowbreak{}",
        "/": r"/\allowbreak{}",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    return "".join(replacements.get(char, char) for char in value)


def theorem_contexts(manuscript: Path, item_count: int) -> list[str]:
    """Return each statement together with immediately following proof blocks."""
    text = manuscript.read_text(encoding="utf-8")
    appendix = re.search(r"(?m)^\\appendix\b", text)
    end_of_parts = appendix.start() if appendix else len(text)
    matches = [match for match in BEGIN_RE.finditer(text) if match.start() < end_of_parts]
    if len(matches) != item_count:
        raise ValueError(
            f"parser disagreement: {item_count} extracted items but {len(matches)} source spans"
        )

    contexts: list[str] = []
    for index, match in enumerate(matches):
        env = match.group(1)
        end_marker = rf"\end{{{env}}}"
        statement_end = text.find(end_marker, match.end())
        if statement_end < 0:
            raise ValueError(f"unclosed {env} at source offset {match.start()}")
        statement_end += len(end_marker)
        next_start = matches[index + 1].start() if index + 1 < len(matches) else end_of_parts
        following = text[statement_end:next_start]
        contexts.append(text[match.start():statement_end] + "\n" + "\n".join(PROOF_RE.findall(following)))
    return contexts


def inject_metadata(
    source: str,
    lean_name: str,
    status: str,
    dependencies: list[str],
    fallback_label: str,
    exact_lean_name: bool = False,
) -> str:
    # Keep the shared source compatible with plasTeX, whose enumitem parser
    # cannot handle optional enumerate labels reliably.
    source = re.sub(
        r"\\begin\{enumerate\}\[[^\]]*\]",
        r"\\begin{enumerate}",
        source,
    )
    source = re.sub(
        r"\\widetilde\\([A-Za-z]+)",
        r"\\widetilde{\\\1}",
        source,
    )
    label_match = re.search(r"\\label\{([^}]+)\}", source)
    if not label_match:
        begin_match = BEGIN_RE.match(source)
        if not begin_match:
            raise ValueError("could not locate theorem environment start")
        synthetic_label = rf"\label{{bp:{fallback_label}}}"
        source = source[: begin_match.end()] + "\n" + synthetic_label + source[begin_match.end() :]
        label_match = re.search(r"\\label\{([^}]+)\}", source)
        assert label_match is not None

    qualified_name = (
        lean_name if exact_lean_name or "." in lean_name else f"{LEAN_LIB}.{lean_name}"
    )
    metadata = [rf"\lean{{{qualified_name}}}"]
    if status == "full":
        metadata.append(r"\leanok")
    if dependencies:
        metadata.append(rf"\uses{{{','.join(dependencies)}}}")
    insertion = "\n" + "\n".join(metadata)
    return source[: label_match.end()] + insertion + source[label_match.end() :]


def generate(manuscript: Path, ledger_path: Path) -> str:
    items = extract_manuscript(manuscript)
    ledger = json.loads(ledger_path.read_text(encoding="utf-8"))
    contexts = theorem_contexts(manuscript, len(items))
    item_keys = [item.label or f"{item.part}:{item.index}" for item in items]
    duplicate_keys = sorted(
        key for key, count in Counter(item_keys).items() if count > 1
    )
    if duplicate_keys:
        raise ValueError(f"duplicate manuscript labels/keys: {duplicate_keys}")
    known_labels = {item.label for item in items if item.label}
    seen_labels: set[str] = set()

    missing = [key for key in item_keys if key not in ledger]
    extra = sorted(set(ledger) - set(item_keys))
    if missing or extra:
        raise ValueError(f"ledger mismatch; missing={missing}, extra={extra}")

    output = [
        "% Generated by scripts/generate_lean_blueprint.py; do not edit by hand.",
        r"\chapter*{Formalization blueprint}",
        r"\addcontentsline{toc}{chapter}{Formalization blueprint}",
        (
            "This blueprint maps every theorem-like statement in the manuscript to its "
            "curated Lean counterpart. A linked declaration is not automatically a "
            "complete formalization: only entries whose ledger status is exactly "
            r"\texttt{full} receive the \texttt{leanok} marker. Partial, conditional, "
            "special-case, and open interfaces remain visibly incomplete."
        ),
    ]
    current_part = ""
    for item, item_key, context in zip(items, item_keys, contexts):
        if item.part != current_part:
            current_part = item.part
            output.extend(["", rf"\chapter{{Part {current_part}}}"])

        record = ledger[item_key]
        if not isinstance(record, dict):
            raise ValueError(f"ledger entry {item_key!r} must be an object")
        for field in ("lean", "status", "lean_remark"):
            if not isinstance(record.get(field), str) or not record[field].strip():
                raise ValueError(
                    f"ledger entry {item_key!r} needs a nonempty string field {field!r}"
                )
        if item.kind == "conjecture" and record["status"] == "full":
            raise ValueError(
                f"open manuscript conjecture {item_key!r} cannot be marked full"
            )
        references: list[str] = []
        for group in REF_RE.findall(context):
            for label in (candidate.strip() for candidate in group.split(",")):
                if label in known_labels and label in seen_labels and label != item.label:
                    if label not in references:
                        references.append(label)

        blueprint_lean = record.get("blueprint_lean", record["lean"])
        if not isinstance(blueprint_lean, str) or not blueprint_lean.strip():
            raise ValueError(
                f"ledger entry {item_key!r} has an invalid 'blueprint_lean' field"
            )
        statement = inject_metadata(
            item.source,
            blueprint_lean,
            record.get("status", ""),
            references,
            item_key,
            exact_lean_name="blueprint_lean" in record,
        )
        status = tex_text(record.get("status", "unspecified"))
        remark = tex_text(record.get("lean_remark", ""))
        output.extend(["", statement])
        if record["status"] != "full":
            output.extend(
                [
                    r"\begin{remark}",
                    rf"\textbf{{Lean alignment.}} \texttt{{{tex_text(record['lean'])}}}. "
                    rf"Ledger status: \texttt{{{status}}}. {remark}",
                    r"\end{remark}",
                ]
            )
        if item.label:
            seen_labels.add(item.label)

    output.append("")
    return "\n".join(output)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manuscript", type=Path, default=Path("master.tex"))
    parser.add_argument(
        "--ledger",
        type=Path,
        default=Path("scripts/theorem_lean_correspondence.json"),
    )
    parser.add_argument(
        "--output", type=Path, default=Path("blueprint/src/content.tex")
    )
    args = parser.parse_args()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(generate(args.manuscript, args.ledger), encoding="utf-8")
    print(f"Wrote {args.output}")


if __name__ == "__main__":
    main()
